### ISSUE TITLE
🔥 部分规则集链接 404

### ISSUE THREAD

**Issue by liby** [SukkaLab/ruleset.skk.moe#1]
## 目前发现的

https://ruleset.skk.moe/List/domainset/apple_cdn.conf
https://ruleset.skk.moe/List/domainset/cdn.conf
https://ruleset.skk.moe/List/domainset/reject_phishing.conf
https://ruleset.skk.moe/List/domainset/reject.conf

https://ruleset.skk.moe/List/ip/china_ip.conf
https://ruleset.skk.moe/List/ip/domestic.conf
https://ruleset.skk.moe/List/ip/neteasemusic.conf
https://ruleset.skk.moe/List/ip/reject.conf
https://ruleset.skk.moe/List/ip/stream.conf
https://ruleset.skk.moe/List/ip/telegram.conf

https://ruleset.skk.moe/List/non_ip/apple_services.conf
https://ruleset.skk.moe/List/non_ip/cdn.conf
https://ruleset.skk.moe/List/non_ip/direct.conf
https://ruleset.skk.moe/List/non_ip/domestic.conf
https://ruleset.skk.moe/List/non_ip/global.conf
https://ruleset.skk.moe/List/non_ip/global_plus.conf
https://ruleset.skk.moe/List/non_ip/neteasemusic.conf
https://ruleset.skk.moe/List/non_ip/reject.conf
https://ruleset.skk.moe/List/non_ip/sogouinput.conf
https://ruleset.skk.moe/List/non_ip/stream.conf
https://ruleset.skk.moe/List/non_ip/telegram.conf

**Comment by SukkaW** [comment]
Fixed.
